name: scalande_project
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  get: ^4.6.1
  intl: ^0.17.0
  get_storage: ^2.0.3
  # dio: ^3.0.10
  dartz: ^0.10.1
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  pedantic: ^1.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^1.0.0
  

flutter:

  uses-material-design: true